### ISSUE TITLE
TypeError: Cannot read property 'state' of undefined at VueComponent.nuxtSocket 

### ISSUE THREAD

**Issue by Tampacz** [richardeschloss/nuxt-socket-io#103]
Hi, got some issue with config nuxt-socket-io.

nuxt.config.js
```
modules: [
    'nuxt-socket-io',
  ],

  io: {
    sockets: [
      {
        name: 'index',
        url: 'http://localhost:7777',
        default: true
      }
    ]
  },
```

component.vue
```
  data () {
    return {
      socket: Object
    }
  },
  mounted () {
    try {
      this.socket = this.$nuxtSocket();
      this.socket.emit('Hello');
      console.log("it works");
    } catch (error) {
      console.log(error)
    }
  }
```

console output:
```
TypeError: Cannot read property 'state' of undefined
    at VueComponent.nuxtSocket (nuxt-socket-io.js?2120:857)
```

**Comment by richardeschloss** [comment]
Hi, the short answer is, you are mostly correct, as of v1.0.22 of the plugin, the plugin will try to register its own Vuex module ([$nuxtSocket vuex module](https://github.com/richardeschloss/nuxt-socket-io)) because it will need that for some features, and in order for it to do that, Vuex state needs to exist. I apologize for not having better documentation or error handling on this at the moment, I was racing to get certain features out. 

Anyway, there are two key changes to make in the code above:

1) Addressing the 'state' issue:
In Nuxt, the following are required:

* vuex - Should exist (i.e., node_modules/vuex folder should be present)
* store/index.js - Defines the vuex state (the Nuxt way)

store/index.js:
```
export const state = () => ({}) // defined state (empty, but defined)
```

I made an [imperfect] assumption that most Nuxt projects will be set up with Vuex (create-nuxt-app usually creates that), but I could have considered the case when it's not.

2) Component.vue code
Your `nuxt.config` looks fine and should work as long as an IO server is running at that url. However, there are only a few minor changes to be made in component:

```
data () {
    return {
     // socket: Object // comment out, not really needed here
    }
  },
  mounted () {
    try {
      this.socket = this.$nuxtSocket();
      this.socket.emit('Hello', 'server', (resp) => { // <-- Use a callback here
          console.log("it works", resp); // If the IO server responds, then it works
     });
    } catch (error) {
      console.log(error)
    }
  }
```

3) socket IO server: (at localhost 7777)
```
socket.on('Hello', (msg, cb) => {
  console.log('msg rxd!', msg)
  cb('I received your msg! Rxd:' + msg)
}) 
```

Can you please let me know if this helps?

**Comment by Tampacz** [comment]
Thank you for the answer.
You're correct. I just needed to define state for vuex.
Keep up the good work.

**Comment by richardeschloss** [comment]
I think I'll but a state check in more I think about it. I just have to think about what other protections and checks I have to put in.

**Comment by richardeschloss** [comment]
Actually, a one-liner in the `store/index.js` is the easiest fix. I prefer that solution rather than taking a risk of breaking existing features.
