### ISSUE TITLE
Hide info log

### ISSUE THREAD

**Issue by TaeyoonKwon** [richardeschloss/nuxt-socket-io#109]
i have disabled console.log from nuxt.config.js and ran nuxt app as production mode.

```
export default {
  // ...
  build: {
    terser: {
      terserOptions: {
        compress: {
          drop_console: true
        }
      }
    },
   // ...
  }
};
 ```

However, It is still logging socket information like below

**[nuxt-socket-io]: connect partner http://localhost:5000**

Is there a way to not show this in console?

**Comment by richardeschloss** [comment]
Hi friend,

My guess is that the plugin currently uses consol**a** instead of consol**e** for the logs. I just pushed a patched plugin.js to branch [issue/109](https://github.com/richardeschloss/nuxt-socket-io/blob/issue/109/io/plugin.js). I'm currently away from being able to test, but can you please try saving that patched plugin.js to your `[node_modules]/nuxt-socket-io` path and let me know if that fixes it?

**Comment by TaeyoonKwon** [comment]
> Hi friend,
> 
> My guess is that the plugin currently uses **consol_a_** instead of **consol_e_** for the logs. I just pushed a patched plugin.js to branch [issue/109](https://github.com/richardeschloss/nuxt-socket-io/blob/issue/109/io/plugin.js). I'm currently away from being able to test, but can you please try saving that patched plugin.js to your `[node_modules]/nuxt-socket-io` path and let me know if that fixes it?

It works! Thank you so much!
