### ISSUE TITLE
socket.io-stream

### ISSUE THREAD

**Issue by standerpm** [richardeschloss/nuxt-socket-io#142]
Good day, I was wondering if its possible to use socket.io-stream with nuxt-socket-io or what is best practice for steaming audio/video? Thank you in advance

**Comment by standerpm** [comment]
Much appreciated! I will give feedback asap

**Comment by richardeschloss** [comment]
Ok, I still want to keep this issue open because my mind is intrigued to see if maybe I can come up with an even better solution than what I originally proposed. In fact, I think socket.io actually has the binary streaming already built-in. https://socket.io/blog/introducing-socket-io-1-0/#binary

**Comment by standerpm** [comment]
Correct me if Im wrong but one cant use fs.createReadStream clientside?

**Comment by richardeschloss** [comment]
Correct, unfortunately due to security concerns, fs can't be used on the client side (i.e., web app's can't access grandma's file system). I think there is a new [File_and_Directory_Entries_API](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API/Introduction) that is out for HTML5, although I'm not entirely familiar with it.

**Comment by richardeschloss** [comment]
Ok, a very basic working example has been pushed to branch [issue/142](https://github.com/richardeschloss/nuxt-socket-io/tree/issue/142).  The example streams a very small "sample.jpg" image so the result can be seen quickly, but any file can be streamed. 

** Server-side **:
A "stream" namespace is configured in `server/io/stream.js:

```js
import { resolve as pResolve } from 'path'
import { createReadStream } from 'fs'
import ss from 'socket.io-stream'

export default function(socket, io) {
  ss(socket).on('sample-image', (stream, data) => {
    const filename = pResolve('./server/sample.jpg')
    createReadStream(filename).pipe(stream)
  })

  return {}
}
```

---

** Client side **:
Client uses socket.io to pass the stream object to the server. This way, when the server writes data to the stream, the client can read from this shared object.

Example in `pages/stream.vue`:

```js
import ss from 'socket.io-stream'
export default {
  data() {
    return {
      imageData: ''
    }
  },
  mounted() {
    const stream = ss.createStream()
    const filename = 'profile.jpg'
    let imageBytes = new Uint8Array()
    this.socket = this.$nuxtSocket({ channel: '/stream' })
    ss(this.socket).emit('sample-image', stream, { name: filename })
    stream
      .on('data', (d) => {
        imageBytes = [...imageBytes, ...d]
      })
      .on('end', () => {
        const imgStr = btoa(String.fromCharCode(...imageBytes))
        this.imageData = `data:image/jpg;base64, ${imgStr}`
      })
  }
}
```

So, important note...this example just flips the direction as to where the file goes. In socket.io-stream's npm page, their example uploads from the browser and the server writes to the filesystem. Here, though, it's just reversed...server reads the image and streams it to the client. (Streams very quickly in this case because the image is small)

Also, even though this example works, I think I'd like to keep this issue open to think of way to make it even easier for people. I'm tinkering with some ideas so that the above snippet can be further simplified.

**Comment by richardeschloss** [comment]
I just pushed branch [issue/142 v2](https://github.com/richardeschloss/nuxt-socket-io/tree/issue/142_v2). I think it may contain a cleaner solution than my first push. It can result in less code for the developer, I think.

First, "socket.io-stream" is listed now as an optionalDependency. So that "npm installing" will alert people to this, if they want it.

Next, there will be no need for people to import socket.io-stream to use it. The module will figure out when to require it or not based on the event it receives. So, I'm suggesting an event prefixed with "~~" to designate a socketStream. This means the namespace file can simply be written like this:

**Server-side**

`server/io/stream.js`:
```js
export default function(socket, io) {
  return {
    '~~sampleImage'(stream, data) { // the "~~" prefix tells nuxt-socket-io to use socket.io-stream
      const filename = pResolve('./server/sample.jpg')
      createReadStream(filename).pipe(stream)  // stream instance made available by socket.io-stream
    },
    'hello'(msg) {  // no prefix here. so this means socket.emit('hello') would invoke this 
      console.log('hello rxd!', msg)
      return 'hello from server!'
    }
  }
}

```

**Client-side**
```js
mounted() {
  const { stream, socket } = this.$nuxtSocket({ 
    channel: '/stream', 
    socketStream: '~~sampleImage' // new: this means to use socket.io-stream to send the "~~sampleImage" event
  })
  /* Now we can work with the shared stream instance */
  stream.on('data', (data) => /* work with data */)

  /* And we can also work with the socket like we've done before */
  socket.emit('hello', console.log) // should emit the "hello" event to be received by the server's "hello" method we defined there.
}
```

I tend to like this a lot because there is no need for the developer to be bothered with the socket.io-stream boilerplate. Just add one more option to nuxtSocket to use it client side. The only thing that *might* be an issue is if anyone already used "~~" in their event names. I chose those characters because they visually look like a stream, and may make the namespace easier to organize. This also made it much easier to implement for me. Just a few conditional statements to make it work. So I hope this will work for people.

**Comment by standerpm** [comment]
This is awesome thank @richardeschloss , do you still need the config in your nuxt.config file?

**Comment by richardeschloss** [comment]
Hey @standerpm , I don't need the config in that file. It only helps to let the full suite of automated tests pass (since those consume it). I've had a better chance to play with this today (all day in fact). I was a little disappointed with what can be done with socket.io-stream. I had my hopes high for it. The stream object it gives us is not a [MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) and I was hoping that MediaStream would have extended the Stream object, so that I could simply pipe the web video capture. 

It turned out to be a bit more challenging than anticipated. All the web video stuff has been designed to work better with WebRTC. I.e., MediaStream is supposed to "just work" with WebRTC. 

Nonetheless, as an example using socket.io, I posted a "screen sharing" example to branch [example/screenShare](https://github.com/richardeschloss/nuxt-socket-io/tree/example/screenShare). The example is quite buggy, but will be enough to explain the challenges. `npm run dev` to launch the server.

* http://localhost:3000/stream --> this will let you start / stop capture of your desktop
* http://localhost:3000/streamView --> this will let you view the screen share.

So, the problem I'm running into is:
1) I can't simply pipe the desktop capture to the socket.io-stream since they're different data types. MediaStream doesn't expose it's underlying buffer. So I can't use socket.io-stream at all for this, or not that cleanly. 
2) Because of (1), I have to resort to using [MediaRecorder](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder) to grabbing chunks of the video stream at a regular interval. The interval is completely arbitrary and not real-time, so this alone probably should have been a reason for giving up on socket.io. Nonetheless, I still tried (3)
3) The streamViewer then receives stream recording as a "blob url" so that it can display it, however, even though I can get the video no problem, I have a problem with the video automatically keeping up with the blob url as it changes.

There was someone else out there who had some success streaming a video [here](https://medium.com/3mig4/stream-a-video-using-express-js-and-socket-io-6c4d1dd263b9). His method was similar, but instead of updating a video element, he instead just captured the most recent frame and transferred that as a still image to redraw a canvas element. Pretty clever, but I was really hoping to have it be video to video (in case people wanted to rewind the screen cast, for example).

I'm sorry I couldn't be more helpful, I may have to return to this at a later date. At the moment I'm just stumped.

**Comment by richardeschloss** [comment]
This doc may also be useful: [addSourceBuffer](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/addSourceBuffer). I think is what I was supposed to use in my example. I'll give it a whirl later this week.

**Comment by richardeschloss** [comment]
Ok, addSourceBuffer and using `appendBuffer` to add data chunks was the trick. The working example has been pushed [examples/screenShare](https://github.com/richardeschloss/nuxt-socket-io/tree/example/screenShare).

This example was accomplished by using socket.io's built-in support for binary streaming, which was kinda neat.  While the example works, in it's current state, there's a noticeable delay of about 1 second or so from the time a change occurs and it's observed on the client; i.e., doesn't have that real-time feel to it.. However, this is still pretty cool.

**Comment by richardeschloss** [comment]
So, since it seems like the binary support is there, socket.io-stream may not be needed. I'll close the issue for the now, and may consider using the examples discussed here for the docs.
