### ISSUE TITLE
HMR with serverMiddleware

### ISSUE THREAD

**Issue by next-direction** [richardeschloss/nuxt-socket-io#149]
Hi,

first of all thanks for this great module, it works really great. I have the following issue with my setup:

Starting with create-nuxt-app v3 the recommended way of using expressJS is with [serverMiddleware](https://nuxtjs.org/guides/configuration-glossary/configuration-servermiddleware).
I used [this](https://github.com/nuxt-community/express-template) template to start my app (which uses serverMiddleware) and I don't get HMR to work properly when using [automatic registration](https://nuxt-socket-io.netlify.app/configuration#automatic-io-server-registration).

I tried the `watch` property inside the` nuxt.config.js` file for the `server/` folder and sub folders (because express code lives inside of `api/` folder in the used starting template). This reloads the server somehow, but changed code inside the `server/io...` folder is not picked up though.

I know that there is [a helpful tip](https://nuxt-socket-io.netlify.app/configuration#io-service-format-important) on how to reload with a separate server/index.js file which unfortunately is no longer present when using a server middleware.

Any idea if HMR could work in this setup? Any help is appreciated.

**Comment by richardeschloss** [comment]
Hi, that project still has many issues, and I don't know how much I would trust that code to work just yet. However, this project here also uses express as the server, and might be the better starting point. (I.e., git cloning this)

To my surprise, now with Nuxt 2.14 and express 4.x, it seems my helpful tip has now become obsolete. I.e., I can now simply run in dev mode and have the HMR work. So I just tested with this project's master branch:

> npm run dev  # runs with Nuxt's server (and HMR works even without the nuxt.config HMR property set)

> npm run dev:server # runs: "dev:server": "cross-env NODE_ENV=development nodemon server/index.js --watch server"

So, I think the important thing on the second line is the "--watch" flag given to nodemon, more than the watch prop in nuxt config. So perhaps "--watch" needs to be set to "api" or something in the express template project.

Your socket.io client may also need to have "reconnection": "true" so that it can try to reconnect after the server disconnects and come back. Otherwise you'll have to manually refresh the browser to see the change.

Can you please let me know how far you get? 

(Also, FWIW...I tend to find test-driven development much faster when developing the code for namespaces, that may provide a much greater developer experience too)

**Comment by next-direction** [comment]
Thanks for the response and your thoughts on that matter.

I tried another approach yesterday by installing nodemon and watch the server folder, but there were several issues with that:

- Every time I changed something in the server files, the server completely restarted which takes forever compared to normal HMR
- Client lost socket connection every time and I had to refresh the page manually (which you already mentioned that this could be a problem)

So I think for now I will go back to use create-nuxt-app 2.15.x where I can still select express as backend server. Then it creates a server/index.js file which I can extend.

The reason for this is I'd like to start from scratch with as little dependencies as possible.

**Comment by richardeschloss** [comment]
First, I applaud your approach for going the lightweight route. A lot of modern software seems to have bloat creep, and I find us minimalists are a dying breed. But, I'm glad to know we still exist. (I try to be a minimalist too, however, I have room to improve) 

Just a heads up, if the socket.io server is piggy backing on Nuxt's server, every HMR server restart will restart the socket.io server too, and can be noticeably slower. To avoid the constant IO disconnect, you may want to run the IO server in it's **own process** on a separate port (3001 perhaps). My library provides a [`register.server`](https://nuxt-socket-io.netlify.app/configuration#io-server-overrides) to help with that (scroll down to the code snippet with `register.server`). 

Still, to avoid browser refresh, you will still probably want the IO client to have "reconnection" to "true" so that when the IO server restarts, no browser refresh is needed.
