### ISSUE TITLE
Possible to register vuex $nuxtSocket earlier?

### ISSUE THREAD

**Issue by orenlande** [richardeschloss/nuxt-socket-io#150]
Hey, we're working on integrating the plugin into our systems.

The situation today as required:

- get data from backend server
- once data retrieved, subscribe the socket to an event
- the data retrieval is being done in the store, once app is booted

so far what we've done is to put the socket initialization on our general layout page (which works just fine), and inside the store in another action dispatch, we're doing the `dispatch("$nuxtSocket/emit", ... )` which works fine, but **only** when we wrap it inside timeout, like this:
```
setTimeout(() => {
  dispatch(
     "$nuxtSocket/emit", // Remember, "emit" is namespaced to "$nuxtSocket"
     {
       ....
     },
  );
}, 1000);
```

on current configuration it's working, but we want to avoid this timeout hack. I think the reason it's because we have to wait for the nuxtSocket module to load, which kicks in in delay. 

as you can see, the module is being loaded in late:
![image](https://user-images.githubusercontent.com/20873769/93755106-6f473980-fc0b-11ea-84dd-9311c1d74039.png)

any suggestions to resolve this issue?

**Comment by richardeschloss** [comment]
I think the code that does this dispatching still needs to know when nuxt-socket-io has initialized. The actual module registration goes pretty fast:

io/plugin.js:
```js
  if (!store.state.$nuxtSocket) {
    debug('vuex store $nuxtSocket does not exist....registering it')
    register.vuexModule({ store }) // as soon as plugin is initialized, and nuxtSocket store does not exist, this runs pretty quickly
  }
```

I believe the delay you see is due to "store/facebook.js" being statically defined in the project workspace, whereas the nuxtSocket store gets added when needed.

The code that does the dispatching should instead check to see that `state.$nuxtSocket` exists before dispatching the emit event. This should avoid the need for the arbitrary timeout.

It's also possible to initialize the $nuxtSocket directly in the vuex action if you'd like. This may be a more appropriate place for it than the layout:

```js
let mySocket = window.$nuxt.$nuxtSocket({...}) // this could be in your vuex actions instead of your layout. but it would require "window" to be defined (so, client-side)
```
