### ISSUE TITLE
Guidance for using in Nuxt API Server

### ISSUE THREAD

**Issue by chrisleyva** [richardeschloss/nuxt-socket-io#155]
Hello @richardeschloss 

Thank you very much for this project. I'd like to try to use this in my project but I'm struggling to see how I can incorporate it into my specific, simple (I think) use case.

I have an Express API as my site's backend, an `api` directory that is configured in **nuxt.config.js** as `serverMiddleware`.

```
- api/
  - index.js
  - modules/
    - moduleA.js
    - moduleB.js
```

Then, inside **moduleA.js** let's say I have the following:

```js
router.post('/resource', async (req, res) => {
  const { items } = req.body;
  for(const [i, item] of items.entries()) {
    // do something with the item
    
    // here, emit something on the socket io connection
    // the Front-end would ideally receive these progress updates
    socket.emit('progress', `${i}/${items.length}`);
  }
});
```

I understand how to use the socket on the front-end. But I'm not sure how to use the socket in my backend, Express API modules.

I don't have a need for the sockets to support Vuex (though I **do** have Vuex setup in my project).
I would appreciate any guidance you can offer with this issue.

Thank you!

**Comment by richardeschloss** [comment]
I personally think (and it's a matter of personal preference / opinion) that it's easier to use [Automatic Server Registration](https://nuxt-socket-io.netlify.app/configuration#automatic-io-server-registration). This way "get" vs. "post" can be abstracted out entirely and the code can stay focused on just passing the messages back and forth (with no need to drill into "req.body"). This way, you can simply move most of the moduleA code to `[appRoot]/server/io` and just change it slightly so that nuxt-socket-io can work with it:

`server/io/moduleA.js`:
``js 
export default function(socket, io) {
  return Object.freeze({
    resource({ items }) {
      /* handle items */
      socket.emit('progress', progress)
    }
  })
}
```

This way, both client and server sides get cleaned up. The client can then just do "socket.emit('resource', { items} )", and that small snippet would handle it.  Will this work for you? 

Otherwise, you have to set up the socket.io server manually in the express code like [this](https://socket.io/docs/server-api/).

**Comment by chrisleyva** [comment]
I appreciate your quick response. I have not yet read the Automatic Server Registration link you included; I'll check it out in a moment and see if it's something feasible for me.

Because my project is a fairly large one, with several routes/pages and REST endpoints, I can't really afford to change the architecture at the moment. I was hoping to be able to keep the current API as-is and _sprinkle in_ sockets as needed.

So, in this case, I envisioned that sending a POST request to my resource endpoint would do what it normally does (manipulate and add to my database), but then **in addition** emit some progress/status messages back to the client.

I understand your point and I would love to use your project but it may require more of a rewrite than I can do at the moment.

I'll take a look at manually setting up the socket.io server, too. Thank you!

**Comment by richardeschloss** [comment]
Ok. If you have to set up manually, this snippet may help:

```js
const server = require('http').createServer(); // or https server depending on what you have
const io = require('socket.io')(server); // your own IO server
server.listen(3000); // you probably have this already
```

However, there will be a tricky part because you're waiting for a socket.io client to be connected, which is technically and fundamentally different, from the REST API client. The communication models are quite different, so a hybrid of the two is usually avoided. Here's an example to explain it:

```js
io.on('connection', (socket) => {
  /* Do something with socket */
})

router.post('/resource', (req, res) => {
  /* Do something with request */

  /* Try to socket.emit stuff */
  socket.emit('progress', progress) // socket not defined in this scope, so this won't work :(

  /* You could perhaps just broadcast to all clients */
  io.emit('progress', progress) // this will go to everyone... so while this should work, I don't know if it's what you want

  io.of('/someChannel').emit('progress', progress) // this may be better...only send to the sockets on channel "someChannel"; this might be the one line solution that gets you going for now (but may not be the best long-term solution)
})
```

Usually the handlers don't go inside one another. I hope this helps.

**Comment by chrisleyva** [comment]
@richardeschloss Thank you very much.
That is helpful. I appreciate the insight and the code examples.

And thanks for your work on this project!
