### ISSUE TITLE
Sockets emitting but not listening to emits

### ISSUE THREAD

**Issue by Syntle** [richardeschloss/nuxt-socket-io#165]
page.vue
```js
mounted() {
  this.socket = this.$nuxtSocket({
    channel: '/queue',
  })

  this.socket.emit('testEmitSend')

  this.socket.on('testEmitReceive', ({ message }) => {
    console.log(message) // Doesn't get logged
  })
}
```
server/io/queue.js
```js
export default function (socket, io) {
  return Object.freeze({
    testEmitSend() {
      console.log('testEmitSend triggered') // This gets logged
      io.emit('testEmitReceive', { message: 'Test Message' })
    }
  })
}
```
I'm not sure why the socket won't listen, I even set up a button that runs `this.socket.emit('testEmitSend')` to test it but the results were the same.

**Comment by richardeschloss** [comment]
There's actually a much easier way to do this, using the emit's callback function:

* Client side: 
```js
this.socket.emit('testEmitSend', msg, (resp) => {
  console.log('handle response', resp) // should show: { message: 'Test Message' } 
})
```

* Server side:
```js
export default function (socket, io) {
  return Object.freeze({
    testEmitSend() {
      console.log('testEmitSend triggered') // This gets logged
      return { message: 'Test Message' }
    }
  })
}
```

Alternatively, if by your original intention, you wish to have separate emitters and listeners, like in your code snippet, you would use "socket.emit" instead of "io.emit" and it would work.

--- 

Side note: Please try to consult the docs and please respect the [Contributing Guidelines](https://github.com/richardeschloss/nuxt-socket-io/blob/master/CONTRIBUTING.md) before opening issues. A lot of work has gone into those, and many times, the answers are already there. There are docs for both this module (nuxt-socket-io) and the underlying library (socket.io).

**Comment by Syntle** [comment]
Sorry, I wasn't specific enough in the example snippet I posted.

I was trying to use `io.to(roomID).emit(...)` and that wasn't working despite the sockets successfully joining the room, I then tried using `io.of('queue').to(roomID).emit(...)` which also didn't work.

The only way I got it to work was by using `io.of('queue').sockets[`/queue#${user1.socketID}`].emit(...)` (twice, one for each user) which in my case isn't too much of an issue since each room only has 2 users but I'm not sure why emitting to rooms doesn't work, it was working when I was using the `/` namespace.
