### ISSUE TITLE
Disconnect event can't call vuex mutation

### ISSUE THREAD

**Issue by TimonPeng** [richardeschloss/nuxt-socket-io#19]
https://github.com/richardeschloss/nuxt-socket-io/blob/55c38b6a65451c9a948e204214bc94cb8e82e6f3/io/plugin.js#L120

```
vuex: {
  mutations: [
    {
      connect: 'socket/onConnect',
      disconnect: 'socket/onDisconnect',
    },
  ]
}
```

connect is works but disconnect can't call vuex mutation.

**Comment by richardeschloss** [comment]
Ok, I'm looking into this right now.

**Comment by richardeschloss** [comment]
Ok, @TimonPeng , please simply restructure your nuxt config options and it will work:
```
vuex: {
  mutations: [
    { connect: 'socket/onConnect' },
    { disconnect: 'socket/onDisconnect' }
  ]
}
```
I.e., an array of objects instead of a single object.

I pushed the branch [issue/19](https://github.com/richardeschloss/nuxt-socket-io/tree/issue/19) which shows a working example. I created a sample "socketStatus" page that will show the connect/disconnect status as stored in Vuex. I hope this helps.

**Comment by TimonPeng** [comment]
@richardeschloss Thank you so much, I feel ashamed.

**Comment by richardeschloss** [comment]
No worries @TimonPeng ! I actually was afraid that maybe you found a security exploit I didn't cover :) I was just re-thinking your concern, and was trying to figure out a better way I can perform the input validation. I probably could have written code that throws an error or provides a message, but I failed to do that :(. I'll continue to think about how I can improve this :)
