### ISSUE TITLE
Joining multiple channels

### ISSUE THREAD

**Issue by mpjraaij** [richardeschloss/nuxt-socket-io#197]
Hi Richard,

I'm struggling a bit with how to set it up multi channels correctly.

In my nuxt config I have:
```
  io: {
    sockets: [
      {
        name: 'default',
        url: process.env.WS_URL,
        default: true,
        persist: true,
        vuex: {
          actions: [
            { UserCreated: 'authentication/register' },
            { UserUpdated: 'authentication/update' },
           ...
          ]
        }
      }
    ]
  },
```

These actions need to keep working at all time.

Now on the fly I want to add new channels. I do that with this piece of code:

```
  addStream(name: String) {
    // @ts-config
    if (this.getStreams.includes(name)) {
      return
    }
    // @ts-config
    this.addStream(name)
    // @ts-ignore
    this.$nuxtSocket({
      name: `stream:${name}`,
      channel: `/stream:${name}`,
      default: false,
      persist: true,
      vuex: {
        actions: [{ StreamUpdated: 'stream/update' }]
      }
    })
  }
```

What I notice however is that one I add the first stream, it works. When I add a second stream, there is no input coming in. It does not seem to actually connect to the second stream and catch input. Even if the console log does output that the stream is connected.

What am I doing wrong?

**Comment by richardeschloss** [comment]
For what it's worth, the code registering the vuex options is here:
https://github.com/richardeschloss/nuxt-socket-io/blob/80bd7195b12eaa1dd51dea0e968e8e06635f848f/io/plugin.js#L1043

And more specifically, registering the vuex actions is here:
https://github.com/richardeschloss/nuxt-socket-io/blob/80bd7195b12eaa1dd51dea0e968e8e06635f848f/io/plugin.js#L739

So, to aid with troubleshooting, setting localStorage.debug to "nuxt-socket-io" should allow the following debug statement to be printed when data is received:
https://github.com/richardeschloss/nuxt-socket-io/blob/80bd7195b12eaa1dd51dea0e968e8e06635f848f/io/plugin.js#L581

And more importantly, the following line should be printed:
https://github.com/richardeschloss/nuxt-socket-io/blob/80bd7195b12eaa1dd51dea0e968e8e06635f848f/io/plugin.js#L590

Note that once an action is registered for a specific event, subsequent actions for the same event won't get registered by design:
https://github.com/richardeschloss/nuxt-socket-io/blob/80bd7195b12eaa1dd51dea0e968e8e06635f848f/io/plugin.js#L587

While design can possibly be up for a healthy debate, I think it's a design I like to prevent duplicate registration (which I think would satisfy more use cases). And, I think it may be better design to key your events based on the stream name any way, and merge them in the vuex action. The action receives data and can easily know which stream it is. So, I'm thinking to solve the issue would be a slight code change:

```js
// @ts-ignore  (Hmm, I'm surprised this was needed.. I can also look into this. the types.d.ts is in the io folder)
this.$nuxtSocket({
  // name: `stream:${name}`, // I think you want to omit this, since only one entry is configured in nuxt.config (the default)
  channel: `/stream:${name}`, // ok
  default: false, // I think you want this true, to use the default socket. (Omitting this line should work too)
  persist: true, // ok
  vuex: {
    // actions: [{ StreamUpdated: 'stream/update' }] // Replace with (see next line)
   actions: [{ `StreamUpdated:${name}`: 'stream/update' }] // this way, each stream has it's own event, but the data each stream sends includes the stream info so the 'stream/update' action knows what to do with it.
  }
})
```

Please let me know how far this gets you. Thank you for your patience, and I apologize for the delay. I was afk for 1 week.

**Comment by mpjraaij** [comment]
@richardeschloss Thanks for your answer. I haven't received a notification and now I'll be off for a week. I'll let you know after I'm back. Thanks!

**Comment by richardeschloss** [comment]
Ok, sounds good! I too will be away from keyboard (or github) for most of the summer but I hope the world can have patience to wait until I get back.

**Comment by mpjraaij** [comment]
Enjoy the summer richard :)

The problem with the code above is `{ `StreamUpdated:${name}`: 'stream/update' }` - as far as I know js es doesn't allow an object name to be assigned dynamically like this. Also my linter is giving quite some errors when I do that.

**Comment by richardeschloss** [comment]
Hi @mpjraaij , sorry, my syntax was off. Here's how you can accomplish it: (basically square brackets are needed around the key to allow variable key names)

```js
  vuex: {
    // actions: [{ StreamUpdated: 'stream/update' }] // Replace with (see next line)
   actions: [{ [`StreamUpdated:${name}`]: 'stream/update' }] // this way, each stream has it's own event, but the data each stream sends includes the stream info so the 'stream/update' action knows what to do with it.
  }
}
```
