### ISSUE TITLE
Vuex socket instance / Global socket problem

### ISSUE THREAD

**Issue by Murked** [richardeschloss/nuxt-socket-io#200]
Hello, i am trying to seek some help on how to go about creating a global socket instance that i can use throughout my app. 

The problem with creating multiple connections in my components is that i have lots of clients connected & my online count is way off. What i am trying to achieve is just make one connection per client & use the one instance throughout my components.

Trying to set a socket in my store using the nuxtServerInit action is creating a connection perfectly, but giving me this error: "Maximum call stack size exceeded".

`
nuxtServerInit ({commit}, context) {
commit('SET_SOCKET', context.$nuxtSocket({ name: "main" }))
}
`

 I have also tried setting a instance to the root inside my main layout component like this:

`
this.$root.diceSocket = this.$nuxtSocket({ name: "main", teardown: false });
`

However, when i try to access this from another component, the "on" & "emit" methods are undefined. But, if i do `console.log(this.$root.diceSocket)` inside my other components, it does show the socket object, which is strange. I must be doing something wrong.

Not sure if im going about this the wrong way, but if there is a way to just connect to my socket one time & reuse it throughout my components, please give me some advice on which direction to go in.

EDIT: I have tried using the `persist: "main"` in both of my components, but its still showing up as 2 connected clients in my socket server, its not connecting just one time.

Thanks!

**Comment by richardeschloss** [comment]
There is a built-in [socket persistence](https://nuxt-socket-io.netlify.app/vuexModule) for this that lets you reuse the same socket throughout the app. Does exactly what you're hoping to do. 

To persist:
```js
mounted() {
  this.socket = this.$nuxtSocket({
    // ...
    persist: 'mySocket', // Persist the socket with label "mySocket"
  })
}
```

To retrieve / re-use:
```js
mounted() { // some other component or page
  this.socket = this.$nuxtSocket({
    // ...
    persist: 'mySocket', // Re-use the socket with label "mySocket"
  })
}
```

**Comment by paramono** [comment]
@richardeschloss Can you please elaborate whether persisting a socket reuses connection?

From what I see, it does not, and @Murked noticed this, too:

>EDIT: I have tried using the persist: "main" in both of my components, but its still showing up as 2 connected clients in my socket server, its not connecting just one time.

I experience the same problem, i.e. if I have 2 components with the same `persist` value, 2 connections will be made to the server. 

Is this behavior intended?

I would like to define a socket globally, so that I can have a single connection throughout the app. So far the workaround I found is to put $nuxtSocket into default layout with `persist: 'mySocket'`, and then emit from components via `this.$store.dispatch` with `label: 'mySocket'` specified, as you mention in the docs: https://nuxt-socket-io.netlify.app/vuexmodule/

But I feel that this code shouldn't be stored in a layout, and there must be a better way.

How would you suggest to reuse the same connection throughout the app?

**Comment by richardeschloss** [comment]
Hi, the plugin maintains the socket state here:

```js
https://github.com/richardeschloss/nuxt-socket-io/blob/ddb286a25349dff8d719467831d591bf79361ecb/io/plugin.js#L34
```

The persistence logic is here:

```js
https://github.com/richardeschloss/nuxt-socket-io/blob/ddb286a25349dff8d719467831d591bf79361ecb/io/plugin.js#L986
```

So, the persisted socket is re-used if it has been stored, *but*, if the socket has disconnected, a reconnection will be made. This may be the 2 connections you're seeing?

If you set `localStorage.debug` to "nuxt-socket-io", that will let you see the debug statements printed. Does this help?
