### ISSUE TITLE
Google Cloud Run deployment

### ISSUE THREAD

**Issue by PMLS3** [richardeschloss/nuxt-socket-io#209]
Please assist, I have tried everything for a solution but still can't deploy to cloud run as soon as I want to use socket. 

My Docker code:

`FROM node:14

WORKDIR /usr/src/app

COPY . ./
RUN npm install

EXPOSE 8080

ENV HOST=0.0.0.0
ENV PORT=8080

RUN npm run build

CMD [ "npm", "run", "start" ]`

My uploads work 100% when I use the normal Nuxt server (SSR) as is, as soon as I want to use Nuxt Socket then I get the following error: Failed to start and then listen on the port defined by the PORT environment variable.

**Comment by richardeschloss** [comment]
Can you please pinpoint what line of code is producing that error?

**Comment by PMLS3** [comment]
Sorry for the late reply, thanks. I Will do that today and give feedback

**Comment by PMLS3** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/62140524/127549008-791b6888-839d-4260-8201-cca72516a270.png)

Deployment failed
ERROR: (gcloud.run.services.update) Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.

**Comment by richardeschloss** [comment]
And what does the node's server code look like? Specifically, the part where it listens for traffic? Is it listening to localhost or all?

**Comment by PMLS3** [comment]
This is the server file
![code](https://user-images.githubusercontent.com/62140524/127594956-236475c0-a84b-4ebd-8417-c19ea9d88e9c.png)
and then the io file
![io](https://user-images.githubusercontent.com/62140524/127595013-39e37112-39b9-41f2-98fb-5d302aa5c84c.png)

**Comment by richardeschloss** [comment]
Oh, that looks like really old nuxt-socket-io code... things have changed since then.. and have been simplified. There's no longer the need to run that server file, just run nuxt and put your io services in a `server/io.js` file. 

Please see https://nuxt-socket-io.netlify.app/configuration#automatic-io-server-registration and consider refactoring your code slightly:
- No longer need the server file (Nuxt runs both server and client code, and we use the Nuxt server)
- The io server file is no longer necessary. Instead, inside of `server/io.js`, it would be a *service* that handles io events, as shown in the provided link. 

(So, with that old server code, the `server.listen` would never trigger the Nuxt's listen event. Nuxt will take care of that on either `nuxt` or `nuxt start`. And then when that listen hook is called, the IO services get registered. )

**Comment by PMLS3** [comment]
Thank you, Richard. You are truly a legend... going through it today. Appreciate your time.

**Comment by richardeschloss** [comment]
I'm going to close this issue because it sounds like the solution will involve updating nuxt-socket-io and updating google cloud configuration(s) (firewall?)

**Comment by PMLS3** [comment]
thank you Richard, it is working
