### ISSUE TITLE
Connecting to rooms

### ISSUE THREAD

**Issue by OfoeApronti** [richardeschloss/nuxt-socket-io#23]
Hi Richard, the nuxt-socket-io is really great. 
Please help me understand the nuxtSocket wrapper and how to use with "rooms"

```
mounted() {
    this.socket = this.$nuxtSocket({
      channel: '/eco',
      reconnection: false
    })
  },
```
if "channel:" refers to namespaces in the socket.io context, how do i create and connect to a "room"

I am referring to a vanilla socket.io implementation below;

```
// client side code
var socket = io.connect();
socket.emit('create', 'room1');

// server side code
io.sockets.on('connection', function(socket) {
  socket.on('create', function(room) {
    socket.join(room);
  });
}); 
```

**Comment by richardeschloss** [comment]
Hi Ofoe!

Thanks for bringing up this question and helping me think about ways to improve it! I appreciate it! This too is something I need a little time to learn about, but I will try to be helpful as soon as I can! 
 My intuition tells me that logic for joining rooms just needs to be handled in the plugin.

I.e., in the plugin, I only destruct the channel, but not the room:
```
function nuxtSocket(ioOpts) {
  const { name, channel = '', ...connectOpts } = ioOpts
  ...
  useSocket.url += channel 
```

may want to be something like:
```
  const { name, channel = '', room = '', ...connectOpts } = ioOpts
  ...
  /* room logic here */
  
```

I have to put a bit of thought into this to make it work right. I just pushed branch `examples/rooms` any some ideas will most likely be there. I have to think about what work the plugin should do, and what the app should do.

Rich

**Comment by OfoeApronti** [comment]
Hi Rich,
Thanks for all the good work, and this awesome library, will be looking forward to the "room" implementation.

Ofoe

**Comment by richardeschloss** [comment]
Update: some basic pages/component skeletons pushed to `examples/rooms`. I'll try to wire up and figure out how to implement the rooms feature tomorrow.

**Comment by richardeschloss** [comment]
Status update: I apologize, it's taking me a little longer to figure this out. I have some automated tests now that should help me troubleshoot faster.

**Comment by richardeschloss** [comment]
HI @OfoeApronti ! Ok, I have finally pushed a working example to show how to properly use:
Please see [examples/rooms](https://github.com/richardeschloss/nuxt-socket-io/tree/examples/rooms) branch. 

To see it in action:
0. Checkout that branch `examples/rooms`: 
> git pull origin; git checkout examples/rooms

1. Launch the dev server:
> `npm run dev:server`

2. Then open two browser tabs to: http://localhost:3000/rooms (those will be two separate clients of the chat application)

3. Join a room, then join a channel in that room. Once both clients are in the same room and channel, they can talk to each other.

Will this approach satisfy your concern? Please let me know if I can close this out. I since the dynamic nature of rooms/channels can be difficult to predict (and perhaps app-specific), it may be challenging for the plugin to absorb this functionality, but I can continue to think about it.

**Comment by olivbau** [comment]
Hey, nice project,
Could you explain the difference between sample and sample2 ?
And i'm not sure to understand the emitBacks system, could you detail the "emitBacks" process ?

Thank you

**Comment by richardeschloss** [comment]
Here's how to think about it. For this case, let's focus on the Vuex options in nuxt.config:
```
emitBacks: ['examples/sample', { 'examples/sample2': 'sample2' }]
```

1. `examples/sample` : This means you have set up your store folder like `store/examples.js` and in it (the "Nuxt way"), you have defined a property `sample` (in my code, it starts as 341). Whenever that value changes *in Vuex*, my module's plugin will "emit back" an event 'examples/sample' with the new value. This means all the server has to do is write: `socket.on('examples/sample', (data) => { /* handle data */})`. I.e,. the front-end does not have to write any extra code in the *app* (cool, right? Less work on front-end). 

2. `{ 'examples/sample2': 'sample2' }`: This is a slighty different format. This means you still have your `store/examples.js` file and have a `sample2` property (in my code, it's 243). When this value changes, it will emit back an event "sample2"; i.e., the one we mapped to. This allows the code to be a bit more flexible. If the server instead were expecting to receive a message 'customSample2' instead of 'sample2', then we would simply just update  `{ 'examples/sample2': 'sample2' }` to `{ 'examples/sample2': 'customSample2' }` in Nuxt config without changing anything else in our front-end code. (relief, right?)

**Comment by olivbau** [comment]
Thank you !

**Comment by richardeschloss** [comment]
Reopening. I have some new ideas I want to try with regards to this. Patience requested :)

**Comment by richardeschloss** [comment]
Status update: branch [feat/namespaces](https://github.com/richardeschloss/nuxt-socket-io/tree/feat/namespaces) has been pushed which I think should address this. I'm still trying different use cases locally. I'm defining a custom arrow syntax to be used in the nuxt.config which I think (I hope) will make sense to users, eventually. Docs will be updated too.

**Comment by richardeschloss** [comment]
Support for namespace config has been added, with the syntax explained in PR #31 . An example for chat rooms that uses the namespace config is shown in PR #32. Documentation will be updated before pushing the release to npm.

**Comment by richardeschloss** [comment]
@OfoeApronti I wrote the following article which helps explain this feature better. https://dev.to/richardeschloss/nuxt-socket-io-how-namespaces-config-may-make-your-life-insanely-easier-23ml

Also, if ok with you, I gave you credit for opening the issue (and I link back to your github profile). Please let me know if you would want me to remove/edit the link from the article.

**Comment by OfoeApronti** [comment]
Merry Christmas Richard,
It is really generous of you, for taking the time to extend the
functionality.

I have read the article, I will test it out this week and provide feedback.
It is ok to link back to my github profile.

Thanks,
Gilbert

**Comment by richardeschloss** [comment]
Ok, cool. I just wrote this article which helps better explain the chat rooms example: https://dev.to/richardeschloss/nuxt-socket-io-how-to-create-a-stealth-mode-chat-application-in-under-10-minutes-1m2g

I have plans in the near-future to improve how the plugin handles IO errors.
