### ISSUE TITLE
socket cannot trigger vuex mutations when client emit message

### ISSUE THREAD

**Issue by liran319** [richardeschloss/nuxt-socket-io#230]
`nuxt.config.js`
```
export default {
  modules: [
    'nuxt-socket-io',
  ],
  io: {
    sockets: [
      {
        name: 'main',
        default: true,
        vuex: {
          mutations: [
            {
              'sendMessage': 'chat/ADD_MESSAGE'
            }
          ]
        }
      }
    ]
  }
}
```
`store/chat.js`
```
export const state = () => {
  return {
    messageList: []
  }
}

export const mutations = {
  ADD_MESSAGE(state, payload) {
    state.messageList.push({...payload})
  },
}
```

`pages/index.vue`
```
<template>
  <input v-model="msg" class="inputMessage" type="text" placeholder="Type here..." @keyup.enter="sendMessage">
</template>
<script>
export default {
  data() {
    return {
      socket: null,
      msg: ''
    }
  },
  mounted() {
    this.socket = this.$nuxtSocket({
      name: 'main'
    })
    this.socket.on('connect', () => {
      console.log('connected', this.socket.connected)  // true
    })
    this.socket.on('updateMessage', (msg, cb) => {
      console.log('@@@ updateMessage', msg)
    })
  },
  methods: {
    sendMessage() {
      if (!this.msg) return
      this.socket.emit('sendMessage', {
        message: this.msg
      })
    }
  },
}
</script>
```

when I input message and press Enter to send message, found that no mutation was triggered. Is there any problem about my code?

**Comment by richardeschloss** [comment]
Hi, please try having the IO server send the message 'sendMessage'. The current design is when events are received by the client from the server, that will trigger the mutation. It's this way because of how socket.io is designed. I.e., if that client emits the 'sendMessage', it's emitting it to the server. It's up to the server to handle it (to, for example, broadcast it to the other clients).

If it were desired for that client to trigger a mutation, it would simply do so directly with the `commit` call.

**Comment by richardeschloss** [comment]
The [docs](https://nuxt-socket-io.netlify.app/configuration#vuex-options-per-socket): 

"As socket.IO events are received..." (means "received from the server")
