### ISSUE TITLE
Missing type definitions for Socket & ManagerOptions

### ISSUE THREAD

**Issue by KilianSSL** [richardeschloss/nuxt-socket-io#251]
I've played around with nuxt-socket-io and tried to follow the documentation as far as possible.
I keep stumbling across the fact that despite i get the connection to the server via
```
  this.socket = this.$nuxtSocket({})
```
it won't let me use `emit` or `on` on the instance via
```
methods: {
  async getMessage () {
    await this.socket?.emit('getMessage', { id: 'abc123' })
  }
},
```
telling me that `Property 'emit' does not exist on type 'NuxtSocket'.`

So after digging around a bit, i found out that in your `nuxt-socket-io` package, the type definitions for 
```
import { ManagerOptions } from 'socket.io-client/build/manager';
import { Socket } from 'socket.io-client/build/socket';
```
leads to `Cannot find module 'socket.io-client/build/socket' or its corresponding type declarations.`.

I have the following versions:
- nuxt: 2.15.8
- nuxt-socket-io: 1.1.24 (downgraded from 2.0.1 cause i thought maybe the new version is the issue)
- socket.io-client: 4.4.1 (automatically installed as dependency of nuxt-socket-io)

EDIT:
https://github.com/richardeschloss/nuxt-socket-io/commit/7b953d522d025077ce4a8f4b2027cc83f5bbe8c5
kinda broke it for me.

It works if i downgrade `socket.io` & `socket.io-client` to 4.1.1.

**Comment by richardeschloss** [comment]
This was fixed in the version to support Nuxt3 (nuxt-socket-io@next), which consumed most of my efforts, because it seemed like the ecosystem was shifting away from Nuxt2 and greatly pushing towards Nuxt3 (primarily because of it finally being on top of Vite).  

To the issue though, the fix needed for this is in 2.x is described in #245 . Today, 2.x users can use patch-package to keep the latest stable version working. In the meantime, can you please try copying the types in the [feat/nuxt3 branch](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/nuxt3/lib/types.d.ts) to your "node_modules/nuxt-socket-io/lib" folder and let me know if that works? Then I can update the v2 branch, although I don't know how much longer I really want to support that version.

**Comment by richardeschloss** [comment]
2.0.2. released with the updated types.
