### ISSUE TITLE
Nuxt3:  No match found for location with path

### ISSUE THREAD

**Issue by PMLS3** [richardeschloss/nuxt-socket-io#253]
Hi @richardeschloss ,

Thanks for the amazing work to get it ready for Nuxt3, I am trying it out now but getting the following error: 

No match found for location with path "/socket.io/?EIO=4&transport=polling&t=NvtdJvE"

npm i nuxt-socket-io@next
v- nuxt-socket-io: 3.0.1

nuxt.config.ts
![config](https://user-images.githubusercontent.com/62140524/150346793-cd42391c-be66-4b0f-af22-6c9c5faabdf9.PNG)

Do we still just drop the io file in server to automatically create?
![server](https://user-images.githubusercontent.com/62140524/150346873-da3af8ad-8083-46e9-bdac-30c00be354e3.PNG)
![io](https://user-images.githubusercontent.com/62140524/150346882-cce00bfd-2ea8-464c-aff9-6d76217fbdfc.PNG)

I created namespaces as such within the io folder. examples.js and index.js
![example](https://user-images.githubusercontent.com/62140524/150347143-7d8bba16-4305-4baf-aa65-b58b4eef33d3.PNG)

Finally I called: 
![examples](https://user-images.githubusercontent.com/62140524/150347196-c0d6001f-a16c-42c6-8c83-5174ebb41c0e.PNG)

Socket server starts on 3001

**Comment by richardeschloss** [comment]
Hi, that error is now showing up due to CORS. Since the Nuxt3 internals changed, for the time being I could no longer piggy back off their server, but had to listen on a different port (which defaults to their port + 1). 

So, if the Nuxt app runs on 3000, and socket.io runs on 3001, if a socket.io client in Nuxt wants to talk to the socket.io server, the socket.io server does so with it's CORS whitelist:

https://github.com/richardeschloss/nuxt-socket-io/blob/cc40373bdce4d925fea1a4d99f47814c5c2d46bf/nuxt.config.js#L100

So the error will go away if you specify CORS options in nuxt.config. 

We'll keep this issue open though because I put a request in to have the listen hook restored and it looks like https://github.com/nuxt/framework/pull/2772 has been merged in.

**Comment by richardeschloss** [comment]
Ok, they indeed restored the "listen" hook and I was able to restore the automated server registration feature. Please update to nuxt-socket-io@3.0.2 just released.

**Comment by PMLS3** [comment]
> Ok, they indeed restored the "listen" hook and I was able to restore the automated server registration feature. Please update to nuxt-socket-io@3.0.2 just released.

Thanks for the quick response and update... legendary
