### ISSUE TITLE
[@next] build / start does not work

### ISSUE THREAD

**Issue by fabianwohlfart** [richardeschloss/nuxt-socket-io#258]
At Nuxt3 npm run build -> npm run start does not register the socket and throws a 404.

**Comment by richardeschloss** [comment]
Hi, I share your frustration with this one, as this something I wanted to work too. Unfortunately, the problem I run into is that the "listen" hook we depend on never gets fired in the built application (during npm start). Even in nuxt.config, hooks.listen never gets fired. It would be nice though if it did because then the socket.io server could automatically start up (and know when to do so).

What I had to resort to for production builds is to use the server registration function in a standalone code and run that concurrently with Nuxt:

standalone.js:
```js
import { register } from 'nuxt-socket-io'

async function startIO () {
  await register.ioServer(null, {
    host: 'localhost',
    port: 3001, // <-- ! has to be different now from Nuxt's port
    cors: {
      origin: 'http://localhost:3000', // <-- means: "allow connections from port 3000"
      methods: ['GET', 'POST']
    }
  })
}
startIO()
```

Then something like this would start both the Nuxt app and socket.io server:
> npm run start && node standalone.js & # start the io server in its own process, to be killed by "pkill node"

I apologize that this probably not the answer you wanted to see. I'll keep my eyes peeled for a better approach. I basically need a way to run this line in production: https://github.com/richardeschloss/nuxt-socket-io/blob/04fe31c1fa0876d24c5e4711cfd203bf3624aa3b/lib/module.js#L206 (once I can, then the extra coding above won't be needed)

**Comment by richardeschloss** [comment]
Update: it appears that the generated code has plans to export the server instance, but currently doesn't:

server/chunks/nitro/server.mjs:
```js
server.listen(port, hostname, (err) => {
  if (err) {
    console.error(err);
    process.exit(1);
  }
  const protocol = cert && key ? "https" : "http";
  console.log(`Listening on ${protocol}://${hostname}:${port}${baseURL()}`); 
  // <-- no hook here
});
const server$1 = {};
export { publicConfig as a, buildAssetsURL as b, buildAssetsDir as c, privateConfig as p, server$1 as s };
```

I've updated the npm build script and added an example lib/standalone.js to show how one can workaround the present issues better. I have faith things will get even easier in the future.

**Comment by fabianwohlfart** [comment]
Thanks for your detailed feedback. Meanwhile I was also digging in Nuxt3 and your Module Code and came to the same conclusion. That the server hooks are not yet implemented and they have plans to do so. Let's hope it will get implemented soon. Thanks!

**Comment by fabianwohlfart** [comment]
fyi https://github.com/nuxt/framework/discussions/1189
