### ISSUE TITLE
Configure on Nuxt-3

### ISSUE THREAD

**Issue by aligzl** [richardeschloss/nuxt-socket-io#259]
Hello i am getting fallowing error while i am trying to create instance;

Node Version: 16.x
Nuxt Socket Version: ^3.0.4

nuxt.config.js:

```
....

modules: [
    "nuxt-socket-io",
  ],

io: {
 sockets: [{
      name: 'main',
      url: 'http://localhost:5000'
    }]
}
....
```

**Error on Console:** Error while mounting app: TypeError: Cannot destructure property '$config' of 'this' as it is undefined.
**Error on Terminal:**  Importing directly from a nuxt.config file is not allowed. Instead, use runtime config or a module. [importing /nuxt.config.ts from index.html]

**Comment by richardeschloss** [comment]
What is the nuxt3 version you're using? What does your page or component look like?

**Comment by aligzl** [comment]
Is it not composition api ready yet?
Options api works as expected :)

I have tried below

```
<script setup>
const { $nuxtSocket } = useNuxtApp();
 onMounted(() => {

   const $socket = $nuxtSocket({
  name: "main"
})
  $socket.on('update', (data) => {
    console.log(data)
  })

  $socket.on('randomUpdate', function(data) {
    console.log(data);
  });

 })
</script>
```

**Comment by richardeschloss** [comment]
I think it should still work with the composition API, but the plugin expects a context, the Nuxt context. A while ago for Nuxt 2.x I did this and it worked: https://github.com/richardeschloss/nuxt-socket-io/blob/589d552e62e46d4449adab43c570a9479c8d430f/components/Composition1.vue#L23.

Now the composition API is integrated into Nuxt3, so I believe the first few lines in the setup tag need to be:
```js
const ctx = useNuxtApp();
onMounted(() => {
   const $socket = ctx.$nuxtSocket(...)
```

Or something similar. Basically, ctx has to be the Nuxt context for the plugin to work (since it depends on other aspects of Nuxt and is trying to be compatible with both Options and Composition API)

**Comment by aligzl** [comment]
The weird thing is destruct $nuxtSocket from context ( useNuxtApp() ) is the issue.

```
// Not works !
const { $nuxtSocket } = useNuxtApp() 
const $socket = $nuxtSocket({ ...  })

/*********************************/

WORKS
const ctx = useNuxtApp();
const $socket = ctx.$nuxtSocket({ ...  })

```
Thanks for your help and great work

**Comment by craigrileyuk** [comment]
> The weird thing is destruct $nuxtSocket from context ( useNuxtApp() ) is the issue.

This is because if useNuxtApp returns a single Ref or Reactive object, then any attempt to destructure them loses the reactivity. So the $nuxtSocket you're getting is likely empty and because it's not reactive, it never updates once the connection is made.

You can use the `toRef(s)` functions to maintain reactivity when destructuring, or do as you've done above and use the whole object.
