### ISSUE TITLE
Possible to keep socket open when switching pages?

### ISSUE THREAD

**Issue by dataexcess** [richardeschloss/nuxt-socket-io#261]
Hello,

Is there a possible way to keep a socket connection open when switching pages in the nuxt app? When I visit my /store page, my $nuxtSocket instance prints "client disconnected from /". This is probably an architectural choice, but I was wondering if it would be possible to keep a connection alive on the application level instead of the page level. 

Thank you!

**Comment by richardeschloss** [comment]
Yes, you can with the [socket persistence](https://nuxt-socket-io.netlify.app/usage#socket-persistence)

**Comment by dataexcess** [comment]
Awesome!!

**Comment by dataexcess** [comment]
Could you help me set up nuxt-socket-io? 

I want to know if I can store the nuxt socket in vuex and call all methods there.. I tried to do it but now I get a lot of 
[vuex] do not mutate vuex store state outside mutation handlers.
errors which are hard to debug. 

maybe the problem is that I am initialising the socket connection on a component, like this:

```
        setupNetwork() {
            if (this.network) { console.log("network already created!"); return }
            let network = new Network(
                this.$nuxtSocket({
                    name: "home",
                    channel: "/",
                    persist: true,
                    reconnection: true,
                })
            );
            this.$store.dispatch("setNetwork", network);
        },
```

Is it a good idea to store the connection in vuex?
Thank you

**Comment by dataexcess** [comment]
I am making a three.js based multiplayer 3D experience. When the user lands on the homepage (for the first time) I want to create the socket connection and initialise the 3D player(s). when the visitor clicks on another page (/shop) and then goes back to the main page (/) I want the connection to persist and the 3D players to be initialised again as they were the last time for a consistent experience. What is the best architecture to accomplish this?

**Comment by dataexcess** [comment]
Ok I understand that I cannot store te socket in vuex and then call all the methods on it back in a component. I need to wrap all the functions in a vuex store itself (I understand the [vuex] do not mutate vuex store state outside mutation handlers. warning now). 

So I will make a vuex store specifically to deal with all te socket connection, but the best way to initialise it would be with nuxtServerInit(), in your documentation you the following: 

_For plugins, asyncData, fetch, nuxtServerInit and Middleware, you can access it from context.$nuxtSocket._

Would you mind giving a concrete code example of how such a nuxtServerInit method would look like, I cannot find a way to get to the context.$nuxtSocket part. 

Thank you!

**Comment by richardeschloss** [comment]
Hi, unfortunately, vuex is not a good store for storing socket.io instances because of the circular JSON structure(s) involved. There will be memory leaks. So, instead, the nuxt-socket-io keeps the socket.io instance(s) that you specify with "persist" in memory. You may find it easier to use a string for "persist" so you can easily reuse it. 

The first time you specify persist, say to "mySocket" (a string), the socket instance will get cached in memory. The second time, say from another page, that socket will be retrieved from memory and reused. So, since the plugin manages the instances, there is no need on your part to store it.

Also, going forward with Nuxt 3, there may be a major paradigm shift away from Vuex and more towards something like `useState()`. I personally find the [`useState()`](https://v3.nuxtjs.org/docs/usage/state/#basic-usage) design pattern to be much more versatile.  Their docs do a better job of explaining it than I can, but basically, I find the approach, while it requires me to unlearn Vuex, actually makes it much easier for me to access/adapt/update global state from pretty much anywhere in my code.

**Comment by dataexcess** [comment]
Yes after searching a bit more I tried out setting a string for the persist value, and it works indeed!
Super cool.

Thank you
