### ISSUE TITLE
Unable to connect to socket when specifying custom io.server svc

### ISSUE THREAD

**Issue by Sebastian-tengai** [richardeschloss/nuxt-socket-io#268]
I bet I'm missing some ridiculous thing but I just cant get it to work, unless modules are in the default `/server/io/` 

Tried to set the server and connect with
`io.server: ['/folder/to/file.ts'] `
this.$nuxtSocket({ channel: '/file' }) // nope

`io.server: { ioSvc: '/folder/to/file.ts'}`
this.$nuxtSocket({ channel: '/ioSvc' }) //nope

`io.server: { ioSvc: '/folder/to} // a file named to.ts is in the folder`
this.$nuxtSocket({ channel: '/ioSvc' }) // nope

if I do have a file inside the (default config)
`/server/io/fileNameSpace.ts`
I can connect to it without problem
this.$nuxtSocket({ channel: '/fileNameSpace' }) // all good

What am I doing wrong here?
I just want to move the "/server" folder from the root to a folder called "Domain". Tried to read the docs 7 times before hitting this =(

Thanks for the good work!

**Comment by richardeschloss** [comment]
The good news is you're able to connect by the default means and it does seem like you're using the library correctly. It also seems like you're on the right track and really close to getting to work. 

My best advice is put a [temporary] console.log statement here: (on your end, this would be in node_modules/nuxt-socket-io/lib/module.js)
https://github.com/richardeschloss/nuxt-socket-io/blob/589d552e62e46d4449adab43c570a9479c8d430f/lib/module.js#L35

```js
console.log('ioSvc', ioSvc) // <-- what is ioSvc being resolved to here?
const { default: Svc, middlewares = {}, setIO = () => {} } = await import(
  ioSvc
 )
```

For what it's worth, this is where the full ioSvc path is being constructed:
https://github.com/richardeschloss/nuxt-socket-io/blob/589d552e62e46d4449adab43c570a9479c8d430f/lib/module.js#L108

If an extension is part of the ioSvc, the full path will be resolved, otherwise, it will search for a supported service (.js, .ts, or .mjs), prioritizing the .js file.

I hope this helps.

**Comment by Sebastian-tengai** [comment]
My man!
Yes, just by looking a bit further down in the file you recommended gave all the clues needed.

It was as simple as

`io.servcer: { ioSvc: './Domain/server'} // in this folder lies a file called the_name_space.ts`

and then for connecting the socket:
`this.$nuxtSocket({ channel: '/the_name_space'  })`

And boom, we're good! 

Thanks a billion!
