### ISSUE TITLE
Question: How can I persist socket object in Vuex?

### ISSUE THREAD

**Issue by Timothy-Y-H-Lee** [richardeschloss/nuxt-socket-io#62]
Hi, Richard Schloss.
First of all thank you for update the nuxt-socket-io recently.

I'd like to save the socket object in store/socketio.js to reuse it
after this.$router.push('/viewer').
Could you help me out?

In Login.vue:
```
export default {
  data () {
    return {
      userID: '',
      userPass: '',
      socketStatus: {}
    }
  },
  mounted () {
    // I'd like to save the 'this.socket' in store/socketio.js. How can I do that? Could you please help me out?
    this.socket = this.$nuxtSocket({
      channel: '/',
      reconnection: true,
      transports: ['websocket'],
      autoConnect: false, // to use the Login button
      emitTimeout: 5000 // 5000 ms
      // sockets = 'login_socket' // for reuse the socket object
    })
  },
  methods: {
    async btnLogin () { // login button clicked by user.
      if (!this.userID || !this.userPass) {
        alert('please enter your ID or Password')
      } else {
        const loginInfo = {
          userID: this.userID,
          userPass: this.userPass
        }

        await this.socket.open( // try to connect
        ).on('connect_error', (err) => {
          if (this.socket) {
            this.socket.close()
            console.dir(err)
          }
        }).on('connect', () => {
          this.socket.emit('try_login', loginInfo, (resp) => { // send 'try_login' message to node.js server
          })
        }
      }
    }
  }
}
```
nuxt.config.js:
```
io: {
  sockets: [
    {
      name: 'main',
      url: process.env.VUE_APP_SOCKET_URL,
      default: true,
      vuex: {
        actions: [{ login: 'socketio/login' }]
        // sockets: [{ login_socket: 'socketio/socket' }] // for save socket object
      }
    }
  ]
}
```
store/socketio.js:
```
export const state = () => ({
  // I'd like to save the socket object from Login.vue to use 'this.$router.push()' or socket.close() or reconnect
  socket: {}
})

export const actions = {
  login ({ commit }, payload) {
    commit('login', payload)
  }
}

export const mutations = {
  login (state, payload) {
    if ((payload.result) && payload.result.trim() !== 'logined') { // check the result (from node.js server)
      // state.socket.close() // I'd like to close to the socket
    } else {
      // If I call this(this.$router.push('/viewer')), my server said: 'client disconnected: ::1 LQK4nqACvJrTexV8AAAB'.
      // So, I'd like to reuse the socket object without disconnected. Could you help me out please?
      this.$router.push('/viewer')
    }
  }
}
```
Node.js Server:
```
socket.on('try_login', (data) => {
  console.log('try_login: ', data);
  socket.emit('login', 
    {
      "result": "logined",
      // "result": "failed",
      "data": {
        "user_id": "test1",
        "name": "user_name",
        "next_page": "viewer"
      }
    }
  );
});
```

in viewer.vue
```
// login_socket.emit('some_message') // send message by reused socket
```

Thanks,

Timothy.

**Comment by richardeschloss** [comment]
I think this might be related to #51 . The constructor also takes `teardown` as an option, which defaults to true. So in order to reuse the component, `teardown` would need to be set to false. I apparently forgot to document that in the README.md file (only in the CHANGELOG). 

```
this.socket = this.$nuxtSocket({ teardown: false })
```

Then, the user is responsible for calling code like `this.socket.close()`. 

This alone may not accomplish the desired task, so I'll continue to investigate this.

**Comment by richardeschloss** [comment]
I personally think it would be cleaner code though to use namespaces. I.e., `/login` namespace for the login communication, and the `/viewer` namespace for that related IO. That way the concerns are separated and far easier to maintain. If someone is on the `/viewer` there might be middleware that runs to check loggedIn state, but even in that case, it's the middleware's concern.

**Comment by richardeschloss** [comment]
@Timothy-Y-H-Lee I just pushed a working example to [feat/reuse](https://github.com/richardeschloss/nuxt-socket-io/tree/feat/reuse) branch that is probably close to what your were trying to do. The `teardown` option had to be set to false, and to prevent duplicate registration of socket listeners, I had to do a check to first see if the socket was stored already in Vuex. If it were not already stored, commit it. For a given socket, we want to make sure we only instantiate it once, otherwise we run the risk of registering multiple socket IO listeners and exceeding the call stack size.

You'll want to see [`pages/login.vue`](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/reuse/pages/login.vue) and [`pages/viewer.vue`](https://github.com/richardeschloss/nuxt-socket-io/blob/feat/reuse/pages/viewer.vue).

In that code, you'll see `login.vue` is the one that commits, and `viewer.vue` is simply able to dispatch actions without re-instantiating nuxtSocket.

The key challenge with trying to get this functionality into the plugin is it would require me to know exactly the Vuex mutation to perform (i.e., "SET_SOCKET") since Vue will throw an error if I attempt to mutate the state directly. Even though the mutation name and socket label can be configured in `nuxt.config`, `this.$nuxtSocket` will still have to be instantiated on at least one page or component. I think at that point in time is when the developer should commit the socket to Vuex store (when he's thinking about it). 

Even though the code works, I still think using namespaces will result in better code that's easier to write. Both approaches (Vuex vs. Local) have their pros and cons.

I hope this helps. I think I'll close the issue for now, and please let me know how far you get.

**Comment by Timothy-Y-H-Lee** [comment]
Hi, Richard Schloss.
First of all thank you for prompt reply and your 'feat/reuse' branch.

The 'teardown: false' code works when I use Nuxt router push to another page in Nuxt.

I try to open the socket with 'open()' in Login.vue but sometimes web console said: 'undefined'

in Login.vue
```
methods: {
    async btnLogin () { // login button clicked by user.
    ...
        await this.socket.open( // try to connect with 'autoConnect: false' option.
        // await this.$store.state.sockets.mySocket.open(
        )
    ...
}
```

so, I've change the Login.vue for 'open()' and without stack overflow as below.
```
...
...
mounted () {
    this.socket = this.$nuxtSocket({
      teardown: false, // ** <-- It works when I use the Nuxt route! Thanks!!
      forceNew: true, // prevent to send multiple messages with 'once()'
      channel: '/',
      timeout: 10000, // I'm not sure It's works when try to connect to the Node server...
      reconnection: true, 
      transports: ['websocket'],
      autoConnect: false, // to use the Login button
      emitTimeout: 5000 // 5000 ms
    })
    // window.$nuxt.$root.socket = null
    window.$nuxt.$root.socket = this.socket // set the global object (I refer to Nuxt loader: 'window.$nuxt.$root.$loading.start()' / 'window.$nuxt.$root.$loading.finish()'
...
...
},
  methods: {
    async btnLogin () { // login button clicked by user.
      ...
      ...
      const loginInfo = {
          userID: this.userID,
          userPass: this.userPass
      }
      await this.socket.open(
      ).once('connect_error', (err) => { // If I use 'on()', send message multiple times to my Node server
        console.dir(err)
      }).once('connect_timeout', (err) => {
        console.dir(err)
      }).once('connect', () => {
        this.socket.emit('try_login', loginInfo, (resp) => { // send 'try_login' message to node.js server
        })
      })
    }
 }
  ...
  ...
```

Thank you so much!

Timothy.

**Comment by Timothy-Y-H-Lee** [comment]
Good!!
`'var reusedSocket = this.$store.state.$nuxtSocket.mySocket // Re-use "mySocket"'`
I think that code good for easy to reuse the socket!
Thank you!!
