### ISSUE TITLE
nuxtSockets dynamic URL's

### ISSUE THREAD

**Issue by milgron** [richardeschloss/nuxt-socket-io#79]
Sorry to post it as an issue Richard! 

It's possible to configure dynamic values for the url's of the sockets in nuxt.config.js? 

`
{
        name: 'example',
        url: DYNAMIC_URL,
 }
`

Thanks!

**Comment by richardeschloss** [comment]
No worries. In the nuxt.config, the url specifies where the socket.io server is located, so that part is static. For the dynamic part, fortunately Vue gives that to us as `this.$route.params`, and it's a matter of sending those params to the IO server.

So, if you've been used to writing a REST api request like:

```
const { id } = this.$route.params
const user = await http.get(`/user/?id=${id}`)
```

With socket.io, you would instead write something like:
```
const { id } = this.$route.params
socket.emit('getUser', { id }, (resp) => {
  // handle user info
}) 
```

Does this help?

**Comment by milgron** [comment]
Yes! It helps a lot :)

Thanks Richard!
